version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/jobs_management
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"

  web_test:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://user:password@db:5432/jobs_management_test
      REDIS_URL: redis://redis:6379/1
      ALLOW_REMOTE_DATABASE_URL: "true"  # Thêm dòng này
    volumes:
      - .:/app
    command: ["bundle", "exec", "rspec"]

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/jobs_management
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app
    command: ["bundle", "exec", "sidekiq"]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000      

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
      - '29094:29094'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://kafka:9092,LISTENER_ALICE://kafka:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://localhost:9092,LISTENER_ALICE://never-gonna-give-you-up:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB

volumes:
  postgres_data:
