apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

# chay command sau tren server de Apply Deployment vào Kubernetes
# kubectl apply -f nginx-deployment.yaml
# Kiểm tra trạng thái Pod
# kubectl get pods