default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000
  username: user
  password: password

development:
  <<: *default
  database: jobs_management_development
  adapter: "makara"
  makara:
    primary_ttl: 5
    sticky: true
    connections:
      - role: master
        name: primary
        host: <%= ENV['DB_HOST'] || 'masterdb' %>
        port: <%= ENV['DB_PORT'] || 5432 %>
        database: <%= ENV['DB_NAME'] || 'jobs_management' %>
        username: <%= ENV['DB_USERNAME'] || 'user' %>
        password: <%= ENV['DB_PASSWORD'] || 'password' %>
      - role: replica
        name: replica        
        host: <%= ENV['DB_HOST'] || 'replicadb' %>
        port: <%= ENV['DB_PORT'] || 5433 %>
        database: <%= ENV['DB_NAME'] || 'jobs_management' %>
        username: <%= ENV['DB_USERNAME'] || 'user' %>
        password: <%= ENV['DB_PASSWORD'] || 'password' %>

test:
  <<: *default
  database: jobs_management_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: jobs_management_production
  adapter: "makara"
  makara:
    primary_ttl: 5
    sticky: true
    connections:
      - role: master
        name: primary        
        host: <%= ENV['DB_HOST'] || 'masterdb' %>
        port: <%= ENV['DB_PORT'] || 5432 %>
        database: <%= ENV['DB_NAME'] || 'jobs_management' %>
        username: <%= ENV['DB_USERNAME'] || 'user' %>
        password: <%= ENV['DB_PASSWORD'] || 'password' %>
      - role: replica
        name: replica        
        host: <%= ENV['DB_HOST'] || 'replicadb' %>
        port: <%= ENV['DB_PORT'] || 5432 %>
        database: <%= ENV['DB_NAME'] || 'jobs_management' %>
        username: <%= ENV['DB_USERNAME'] || 'user' %>
        password: <%= ENV['DB_PASSWORD'] || 'password' %>
