development:
  client_id: "rails-app"
  brokers:
    - localhost:9092

test:
  client_id: "rails-app"
  brokers:
    - localhost:9092

production:
  client_id: "rails-app"
  brokers:
    - kafka1.myapp.com:9092
    - kafka2.myapp.com:9092
    - kafka3.myapp.com:9092
